--problem 1
SELECT sysdate, 'Thalia Edwards' FROM dual;
CREATE TABLE STUDENT (
ST_NUMBER NUMBER(6) CONSTRAINT STUDENT_ST_NUMBER_PK PRIMARY KEY,
ST_LAST VARCHAR2(35) NOT NULL,
ST_FIRST VARCHAR2(25),
ST_DOB DATE);
DESC STUDENT;

--problem 2
SELECT sysdate, 'Thalia Edwards' FROM dual;
CREATE TABLE VENDOR (
VEND_NUMBER NUMBER(5) CONSTRAINT VENDOR_VEND_NUMBER_PK PRIMARY KEY,
VEND_NAME VARCHAR2(35) NOT NULL
);
DESC VENDOR;

--problem 3
SELECT sysdate, 'Thalia Edwards' FROM dual;
CREATE TABLE PRODUCT
(
PROD_CODE NUMBER(5) CONSTRAINT PRODUCT_PROD_CODE_PK PRIMARY KEY,
PROD_DESC VARCHAR2(35)
);
DESC PRODUCT;

--problem 4
SELECT sysdate, 'Thalia Edwards' FROM dual;
CREATE TABLE MANUFACTURE
(
PROD_CODE NUMBER(5),
VEND_NUMBER NUMBER(5),
MANU_CODE NUMBER(5),
FOREIGN KEY (PROD_CODE) REFERENCES PRODUCT(PROD_CODE),
FOREIGN KEY (VEND_NUMBER) REFERENCES VENDOR(VEND_NUMBER),
CONSTRAINT MANU_CODE_PK PRIMARY KEY(PROD_CODE, VEND_NUMBER)
);
DESC MANUFACTURE;

--problem 5
SELECT sysdate, 'Thalia Edwards' FROM dual;
ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_PROD_DESC_UK UNIQUE (PROD_DESC);
DESC PRODUCT;

--problem 6
SELECT sysdate, 'Thalia Edwards' FROM dual;
ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_ST_DOB_CK CHECK(ST_DOB < '01-JAN-2000');
DESC STUDENT;