--problem 1
SELECT sysdate, 'Thalia Edwards' FROM dual;
CREATE TABLE THALIA_EDWARDS (
TAE_ORDERID CHAR(2) CONSTRAINT THALIA_EDWARDS_TAE_ORDERID_PK PRIMARY KEY,
TAE_ORDERNUMBER NUMBER(10) CONSTRAINT THALIA_EDWARDS_TAE_ORDERNUMBER_UK UNIQUE NOT NULL,
TAE_ORDERITEM VARCHAR2(30) NOT NULL,
TAE_ORDERDATE DATE NOT NULL
);
DESC THALIA_EDWARDS;

--problem 2
SELECT sysdate, 'Thalia Edwards' FROM dual;
INSERT INTO THALIA_EDWARDS VALUES (
'01', 5964947930, 'Shower Head', '04-OCT-2025'
);
SELECT * FROM THALIA_EDWARDS;

--problem 3
SELECT sysdate, 'Thalia Edwards' FROM dual;
INSERT INTO THALIA_EDWARDS VALUES (
'02', 5698741025, 'Black Hoodie', '04-OCT-2025'
);
SELECT * FROM THALIA_EDWARDS;

--problem 4
SELECT sysdate, 'Thalia Edwards' FROM dual;
UPDATE THALIA_EDWARDS 
SET TAE_ORDERDATE = '14-SEP-2025'
WHERE TAE_ORDERDATE = '04-OCT-2025'
SELECT * FROM THALIA_EDWARDS;

--problem 5
SELECT sysdate, 'Thalia Edwards' FROM dual;
DELETE FROM THALIA_EDWARDS
WHERE TAE_ORDERID = '01';
SELECT * FROM THALIA_EDWARDS;

--problem 6
SELECT sysdate, 'Thalia Edwards' FROM dual;
COMMIT;
SELECT * FROM THALIA_EDWARDS

--problem 7
SELECT sysdate, 'Thalia Edwards' FROM dual;
ROLLBACK;

--problem 8
SELECT sysdate, 'Thalia Edwards' FROM dual;
DROP TABLE THALIA_EDWARDS;