--problem 1
SELECT sysdate, 'Thalia Edwards' FROM dual;

SELECT FIRSTNAME, LASTNAME
FROM CUSTOMERS
WHERE STATE = 'FL';

--problem 2
SELECT sysdate, 'Thalia Edwards' FROM dual;

SELECT CUSTOMER#
FROM ORDERS
WHERE SHIPCOST BETWEEN 0 AND 3;

--problem 3
SELECT sysdate, 'Thalia Edwards' FROM dual;

SELECT TITLE
FROM BOOKS
WHERE CATEGORY IN ('CHILDREN', 'COMPUTER', 'COOKING');

--problem 4
SELECT sysdate, 'Thalia Edwards' FROM dual;

SELECT FIRSTNAME, LASTNAME
FROM CUSTOMERS
WHERE LASTNAME LIKE 'MC%';

--problem 5
SELECT sysdate, 'Thalia Edwards' FROM dual;

SELECT CUSTOMER#, FIRSTNAME, LASTNAME
FROM CUSTOMERS
WHERE EMAIL IS NULL;

--problem 6
SELECT sysdate, 'Thalia Edwards' FROM dual;

SELECT CUSTOMER#, FIRSTNAME, LASTNAME
FROM CUSTOMERS
WHERE REFERRED IS NOT NULL AND EMAIL IS NOT NULL;

--problem 7
SELECT sysdate, 'Thalia Edwards' FROM dual;

SELECT TITLE, COST
FROM BOOKS
WHERE CATEGORY IN ('COMPUTER', 'COOKING') AND COST < 20
ORDER BY COST;