-- Chapter 5 Problems
--problem 1
SELECT sysdate, 'Thalia Edwards' FROM dual;

INSERT INTO ORDERS VALUES (
 1021, 1009, '20-JUL-2009', NULL, NULL, NULL, NULL, NULL, NULL
);

SELECT * 
FROM ORDERS
WHERE ORDER# = 1021;

-- problem 2
SELECT sysdate, 'Thalia Edwards' FROM dual;

UPDATE ORDERS
SET ZIPCODE = 33222
WHERE ORDER# = 1017;

SELECT * 
FROM ORDERS
WHERE SHIPZIP = 33222;

-- problem 3
SELECT sysdate, 'Thalia Edwards' FROM dual;

COMMIT;

-- problem 4
SELECT sysdate, 'Thalia Edwards' FROM dual;

INSERT INTO ORDERS VALUES (
 1022, 2000, '06-AUG-2009', NULL, NULL, NULL, NULL, NULL, NULL
);

SELECT * 
FROM ORDERS
WHERE ORDER# = 1022;
	
-- problem 5
SELECT sysdate, 'Thalia Edwards' FROM dual;

INSERT INTO ORDERS VALUES (
1023, 1009, NULL, NULL, NULL, NULL, NULL, NULL, NULL
);

SELECT * 
    FROM ORDERS
    WHERE ORDER# = 1023;

-- problem 6
SELECT sysdate, 'Thalia Edwards' FROM dual;

SAVEPOINT ONE;

UPDATE BOOKS
SET COST = '&COST'
WHERE ISBN = '&ISBN';

SELECT * 
FROM BOOKS
WHERE ISBN = 1059831198;

-- problem 8
SELECT sysdate, 'Thalia Edwards' FROM dual;

ROLLBACK TO ONE;

SELECT * 
FROM BOOKS
WHERE ISBN = 1059831198;

-- problem 9
SELECT sysdate, 'Thalia Edwards' FROM dual;

SAVEPOINT TWO;

DELETE FROM ORDERITEMS
WHERE ORDER# = 1005;

DELETE FROM ORDERS
WHERE ORDER# = 1005;

SELECT * FROM ORDERS;

SELECT * FROM ORDERITEMS;

-- problem 10
SELECT sysdate, 'Thalia Edwards' FROM dual;

ROLLBACK TO TWO;

SELECT * 
FROM ORDERS
WHERE ORDER# = 1005;

-- Chapter 8 Problems
-- problem 1
SELECT sysdate, 'Thalia Edwards' FROM dual;

SELECT LASTNAME, FIRSTNAME, STATE
FROM CUSTOMERS
WHERE STATE = 'NJ';

-- problem 2
SELECT sysdate, 'Thalia Edwards' FROM dual;

SELECT ORDER#, SHIPDATE
FROM ORDERS
WHERE SHIPDATE > '01-APR-2009';

-- problem 3
SELECT sysdate, 'Thalia Edwards' FROM dual;

SELECT TITLE, CATEGORY
FROM BOOKS
WHERE CATEGORY != 'FITNESS';

-- problem 4
SELECT sysdate, 'Thalia Edwards' FROM dual;

SELECT CUSTOMER#, LASTNAME, STATE
FROM CUSTOMERS
WHERE STATE IN ('GA', 'NJ')
ORDER BY LASTNAME ASC;

SELECT CUSTOMER#, LASTNAME, STATE
FROM CUSTOMERS
WHERE STATE = 'GA' OR STATE = 'NJ'
ORDER BY LASTNAME ASC;

-- problem 5
SELECT sysdate, 'Thalia Edwards' FROM dual;

SELECT ORDER#, ORDERDATE
FROM ORDERS
WHERE SHIPDATE <= '01-APR-2009';

SELECT ORDER#, ORDERDATE
FROM ORDERS
WHERE SHIPDATE < '01-APR-2009' OR SHIPDATE = '01-APR-2009';

-- problem 6
SELECT sysdate, 'Thalia Edwards' FROM dual;

SELECT LNAME, FNAME
FROM AUTHOR
WHERE LNAME LIKE '%IN%';

-- problem 7
SELECT sysdate, 'Thalia Edwards' FROM dual;

SELECT LASTNAME, CUSTOMER#
FROM CUSTOMERS
WHERE REFERRED IS NOT NULL;

-- problem 8
SELECT sysdate, 'Thalia Edwards' FROM dual;

SELECT TITLE, CATEGORY
FROM BOOKS
WHERE CATEGORY LIKE '%CHILDREN%' OR CATEGORY LIKE '%COOKING%';

SELECT TITLE, CATEGORY
FROM BOOKS
WHERE CATEGORY IN ('CHILDREN', 'COOKING');

SELECT TITLE, CATEGORY
FROM BOOKS
WHERE CATEGORY = 'CHILDREN' OR CATEGORY = 'COOKING';

-- problem 9
SELECT sysdate, 'Thalia Edwards' FROM dual;

SELECT ISBN, TITLE
FROM BOOKS
WHERE TITLE LIKE '_A_N%';

-- problem 10
SELECT sysdate, 'Thalia Edwards' FROM dual;

SELECT TITLE, PUBDATE
FROM BOOKS
WHERE PUBDATE BETWEEN '01-JAN-2005' AND '31-DEC-2005'
AND CATEGORY = 'COMPUTER';

SELECT TITLE, PUBDATE
FROM BOOKS
WHERE PUBDATE >= '01-JAN-2005' AND PUBDATE <= '31-DEC-2005'
AND CATEGORY = 'COMPUTER';

SELECT TITLE, PUBDATE
FROM BOOKS
WHERE CATEGORY LIKE 'COMP%'
AND PUBDATE BETWEEN '01-JAN-2005' AND '31-DEC-2005';